Use app name in message. Add short hash for message.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,16 +4,22 @@
 set -e
 
 env_dir=$(cd "$3/" && pwd)
-key=HONEYCOMB_WRITE_KEY
 
-export "$key=$(cat "${env_dir}/${key}")"
-[[ -z "${!key}" ]] && echo "-----> ${key} is missing or empty: unable to continue." && exit 1
+# gather environment variables
+for key in HONEYCOMB_WRITE_KEY HEROKU_APP_NAME; do
+  [[ -f "${env_dir}/${key}" ]] && export "$key=$(cat "${env_dir}/${key}")"
+  [[ -z "${!key}" ]] && echo "-----> ${key} is missing or empty: unable to continue." && exit 1
+done
 
+# get short hash of SOURCE_VERSION
+short_hash=$(git rev-parse --short ${key})
+
+# set marker
 echo "-----> Creating deploy Honeycomb Marker for ${SOURCE_VERSION}"
 curl https://api.honeycomb.io/1/markers/nomics \
   -X POST \
   -H "X-Honeycomb-Team: ${HONEYCOMB_WRITE_KEY}" \
-  -d "{\"message\":\"nomics.com - ${SOURCE_VERSION}\", \"type\":\"deploy\"}" \
+  -d "{\"message\":\"${HEROKU_APP_NAME}:${short_hash}\", \"type\":\"deploy\"}" \
   >/dev/null
 
 echo "       Done!"
